{
    parserClass="io.chengguo.api.debugger.lang.parser.ApiParser"
    parserUtilClass="io.chengguo.api.debugger.lang.parser.ApiParserUtil"

    extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

    psiClassPrefix="Api"
    psiImplClassSuffix="Impl"
    psiPackage="io.chengguo.api.debugger.lang.psi"
    psiImplPackage="io.chengguo.api.debugger.lang.psi.impl"

    elementTypeHolderClass="io.chengguo.api.debugger.lang.psi.ApiTypes"
    elementTypeClass="io.chengguo.api.debugger.lang.psi.ApiElementType"
    tokenTypeClass="io.chengguo.api.debugger.lang.psi.ApiTokenType"

    tokens=[
        FLAG_TITLE       =   '##'
        FLAG_DES         =   '+++'
    ]
}

Root ::= (ApiBlock|LINE_COMMENT)*

private ApiBlock ::= Info

private Info ::= Title

Title ::= '##' TITLE_RAW_STRING

//private Description ::=  FLAG_DES TITLE_RAW_STRING FLAG_DES
