{
  classHeader="license.txt"
  generate=[java="8" names="long" visitor-value="R"]

  parserClass="io.chengguo.api.debugger.lang.parser.ApiParser"
  parserUtilClass="io.chengguo.api.debugger.lang.parser.ApiParserUtil"

  implements="io.chengguo.api.debugger.lang.psi.ApiElement"
  extends="io.chengguo.api.debugger.lang.psi.impl.ApiElementImpl"

  psiClassPrefix="Api"
  psiImplClassSuffix="Impl"
  psiPackage="io.chengguo.api.debugger.lang.psi"
  psiImplPackage="io.chengguo.api.debugger.lang.psi.impl"
  psiImplUtilClass="io.chengguo.api.debugger.lang.psi.impl.ApiPsiImplUtil"

  elementTypeHolderClass="io.chengguo.api.debugger.lang.psi.ApiTypes"
  elementTypePrefix="Api_"
  elementTypeClass="io.chengguo.api.debugger.lang.psi.ApiElementType"
  tokenTypeClass="io.chengguo.api.debugger.lang.psi.ApiTokenType"

  tokens=[
    COLON       = ":"
    SCHEME_SEPARATOR    = "://"
    HTTP       = "http"
    HTTPS       = "https"
  ]
}

apiFile ::= api_*

private api_ ::= (item|LINE_COMMENT|MULTILINE_COMMENT|CRLF)

item ::= description request

description ::= TITLE

request ::= request_line header_field SEPARATOR //(KEY? SEPARATOR VALUE?) | KEY

request_line ::= METHOD request_target

header_field ::= (HEADER_FIELD_NAME ':' HEADER_FIELD_VALUE)*

request_target ::= scheme '://' host ':'  /*port path_absolute*/
scheme ::= 'http' | 'https'
host ::= HOST_VALUE
port ::= PORT_SEGMENT
path_absolute ::= ('/' SEGMENT)*

//varable ::= '{{' IDENTIFIER '}}'